### ISSUE TITLE
 Cannot find module 'e:\Projects\Web\genart\first\e' from '_fake.js' required by e:\Projects\Web\genart\first\_fake.js

### ISSUE THREAD

**Issue by mblandr** [mattdesl/canvas-sketch#112]
After installing canvas-sketch-cli trying to canvas-sketch sketch.js --new --open I got this error.
node 12.18.1, but with 14.3.0 it's the same
![Error](https://user-images.githubusercontent.com/42862020/97958827-b867dd00-1db6-11eb-9043-062eb42c7442.png)

**Comment by Forpee** [comment]
Need help also

**Comment by msup** [comment]
Same problem here.

Running on  W10, tried Node v12, latest version and the v14.16.1

Importing the canvas-sketch.js from "https://unpkg.com/canvas-sketch@latest/dist/canvas-sketch.umd.js" works.

**Comment by stevemk42** [comment]
Hello @msup ..
Sorry Im kind of new here.. please can you list steps about how you did this ?
Thanks in advance

**Comment by stevemk42** [comment]
Ok @msup .. I finally made it work out for me too. thanks.
(I was still using "require" ahead.. don't know why, but I finally figured it out)
Only remaining problem now is to work with the util (canvas-sketch-util) library.. since I need random from it. And The one from unpkg looks short, and with no random object into it..

Any help, anyone, please ? thanks in advance

**Comment by mattdesl** [comment]
I think this might be fixed in latest version. Please update and comment if you see it again.

If you are having trouble with installation, see [this comment](https://github.com/mattdesl/canvas-sketch/issues/96#issuecomment-1231548822).

### To update:

If you've previously installed the CLI tool globally:

```sh
npm install canvas-sketch-cli@latest --global
```

Or locally:

```sh
npm install canvas-sketch-cli@latest --save-dev
```

Let me know if any issues persist.

**Comment by tammytwolegs** [comment]
I have the same issue, neither of these work:

Globally: 
npm install canvas-sketch-cli@latest --global

Or locally:

npm install canvas-sketch-cli@latest --save-dev

I keep getting this error 

<img width="565" alt="Screenshot 2024-06-19 at 14 14 07" src="https://github.com/mattdesl/canvas-sketch/assets/23291954/d6a3e7f2-8923-4083-a32d-d1e78d70c29b">
