### ISSUE TITLE
[Idea] Prevent frames overwriting with timestamps

### ISSUE THREAD

**Issue by fturcheti** [mattdesl/canvas-sketch#12]
When exporting images while sketching, we get timestamped image files, so we don't have to worry about overwriting them while we iterate over our sketching and exporting process.

But when we are exporting animated frames, this is different. As frames are exported as `[frame-number].[extension]`, if we export the frames for a certain state, then tweak the code and export frames again, we'll overwrite the previous frame files with the new ones.

To prevent this overwriting, I have some ideas:

1. Export the frames to a timestamped folder in the current export path. This way, instead of getting frames like this:

    ```
    ~/Downloads/0001.png  
    ~/Downloads/0002.png  
    ~/Downloads/0003.png
    ```

    we'd get this:

    ```
    ~/Downloads/2018.08.01-11.56.00/0001.png  
    ~/Downloads/2018.08.01-11.56.00/0002.png  
    ~/Downloads/2018.08.01-11.56.00/0003.png
    ```

2. Or export the frames with a timestamp prefix. This way we'd get files like this:

    ```
    ~/Downloads/2018.08.01-11.56.00-0001.png  
    ~/Downloads/2018.08.01-11.56.00-0002.png  
    ~/Downloads/2018.08.01-11.56.00-0003.png
    ```

**Comment by mattdesl** [comment]
I actually like them overriding because I don't mind losing frames, and it means I can always re-run the following command to generate a new MP4 + GIF:

```sh
canvas-sketch-gif tmp/ && canvas-sketch-mp4 tmp/
```

But I can see why you would not want them to override. How about if a command-line flag is passed that will trigger animations to be exported into a sub-folder, using the same file name scheme as single frame exports? I guess the question is, what do we call this flag?

**Comment by fturcheti** [comment]
I didn't know about `canvas-sketch-gif` and `canvas-sketch-mp4`. Now I understand why you want to keep the frames named as a simple number sequence.

Would it be possible to have a command to export all frames and automatically encode them in a gif or mp4?

**Comment by mattdesl** [comment]
So - I did an experiment in another tool, where instead of creating frames, it streamed each frame into a GIF file. This was much, much slower, to the point that I ended up just getting annoyed with it and going back to ffmpeg. I'm not sure why it was so slow (it doesn't seem like it should be), so perhaps that is worth investigating again. Another major issue is that the current ffmpeg GIF encoding is really high quality (using two passes & a color palette), and it's hard to reproduce that level of GIF quality with a JS encoder.

As for automatically running ffmpeg after export, it's certainly possible. But I don't expect all users of `canvas-sketch` to have ffmpeg installed, so it will create a lot of issues and makes for a bit of vendor lock-in.

I'm definitely interested to explore ways to make this workflow a bit more automatic & efficient. For example, maybe the CLI could support `--ffmpeg` option which renders individual frames to a temporary directory, then encodes & exports GIF and MP4 files, then deletes the temporary frames/directory. Or, maybe I could stream the data directly into `ffmpeg` rather than creating intermediate frames.

**Comment by fturcheti** [comment]
After using `canvas-sketch` now and then during the last months, I don't think this is a relevant idea. Actually, today I wouldn't use this tool the way I described the issue back then. After the addition of the `--stream` option, that's the way to go when iterating over animation sketches.
