### ISSUE TITLE
Syntax for custom templates

### ISSUE THREAD

**Issue by Bjvanminnen** [mattdesl/canvas-sketch#13]
I was happy to see that one can easily create their own templates for sketches, though I was a little surprised by the syntax. For others who might be running into this, the approach is to do the following:

`canvas-sketch --new --open < path/to/my-custom-template.js`

FWIW, my initial expectation was that I would be able to pass the path to my template as an argument, i.e. `canvas-sketch --new --open --template=./path/to/my-custom-template.js`.

As the documentation gets more flushed out, I imagine this will be covered. Feel free to close this issue in the interim.

Thanks!

**Comment by mattdesl** [comment]
Good idea! I could add a feature so that a path could be used for the template option. I could also maybe support more advanced use case, like installing templates straight from npm or GitHub. 

As for your first note, stdin is more useful for something like piping from clipboard. You can copy sketch code (eg from examples) and then run:

`pbpaste | canvas-sketch -n`

And it will generate & setup a new file from clipboard contents.

**Comment by mattdesl** [comment]
In `canvas-sketch-cli@1.0.16` you should be able to specify a template by file:

e.g.

```js
canvas-sketch src/my-sketch.js --new --open --template=./templates/cool.js
```

To update:

```sh
npm install canvas-sketch-cli@1.0.16 -g
```
