### ISSUE TITLE
Rendering differences in export and browser on high DPI monitor

### ISSUE THREAD

**Issue by Caged** [mattdesl/canvas-sketch#15]
👋 Thanks for your work on this, it looks promising!  I wanted to report an issue I noticed when working with a high dpi canvas. Particularly, I noticed some rendering differences when viewing in the browser vs when exporting on my high DPI screen (Macbook Pro Retina).   Here's the sample sketch:

``` js
const canvasSketch = require('canvas-sketch')

const settings = {
  dimensions: [500, 500]
}

const sketch = () => {
  return ({context: ctx, width, height}) => {
    ctx.fillStyle = 'white'
    ctx.strokeStyle = 'black'
    ctx.lineWidth = 0.5

    const rings = width / 50
    const step = 25
    for (let i = 0; i < rings; i++) {
      const size = width - step * i * 2
      ctx.rect(step * i, step * i, size, size)
      ctx.stroke()
    }
  }
}

canvasSketch(sketch, settings)
```

### What it looks like in the browser (Chrome)

Note that the line width is much larger than what would typically be considered a `lineWidth` of `0.5`.  
Also the color fades towards the center, even though `strokeStyle` remains constant. 

<img width="596" alt="screen shot 2018-08-10 at 10 29 40 pm" src="https://user-images.githubusercontent.com/25/43988548-eef54896-9cec-11e8-8a4b-95a725ca22b6.png">

### What the export looks like
When doing a `⌘+S` save, the stroke color appears to be correct, but the line width still looks a bit too thick.

![2018 08 10-22 25 07](https://user-images.githubusercontent.com/25/43988561-6d4d7150-9ced-11e8-86e7-86b1408d1fa5.png)

### Hijacking the pixel ratio 

The issue appears to be related to how the `style` attribute is calculated.  Typically I've used something like the function below to set a canvas to "high dpi mode."  You can call this function at the top of your sketch function to apply it. 

```js
function hdpi(canvas, ctx, width, height) {
  canvas.width = width * devicePixelRatio
  canvas.height = height * devicePixelRatio
  canvas.style.width = `${width}px`
  canvas.style.height = `${height}px`
  ctx.scale(devicePixelRatio, devicePixelRatio)
}
```
The main difference is that that _x_ is always `devicePixelRatio * x` where `x` is `width` or `height`.  When applying this method to a sketch, I get a render closer to what I would expect.

<img width="650" alt="screen shot 2018-08-10 at 10 41 39 pm" src="https://user-images.githubusercontent.com/25/43988623-976a16c2-9cee-11e8-8c96-7e58f8b130e3.png">

Though, the save file is now 2x the desired size and you can't resize the browser window because the hijack is lost.  

![2018 08 10-22 43 19](https://user-images.githubusercontent.com/25/43988632-d0108c40-9cee-11e8-8829-88d7f56516ab.png)

The core issue appears to be that the `width` and `height` attribute should always be 2x (`devicePixelRatio`) of the style width and height for an accurate representation on high DPI monitors.  

``` html
<canvas width="500" height="500" style="width: 500px; height: 500px;"></canvas>
```

**Comment by mattdesl** [comment]
Hey there! Thanks for trying `canvas-sketch`. By default, I've disabled high DPI when a `dimension` is specified, as usually it would cause confusion when a `[ 500, 500 ]` pixel canvas is exported at a different size depending on the machine. This way, when a user specifies a 500x500 px dimension, the output PNG file is also 500x500px.

However, I think in this case there are three considerations that are causing rendering to look a bit weird on export:

1. You are using a lineWidth of 0.5 — anything smaller than 2.0 might render with a bit of transparency in Chrome, rather than pure/solid colour. Seems like a Chrome bug or perhaps limitation of anti-aliased line rendering.
2. Your canvas is not cleared at the beginning of a frame, so subsequent renders after the first may produce different results, as the semi-transparent lines are being drawn on top of previous renders.
3. You should specify `ctx.beginPath()` before starting each rectangle, otherwise all the `rect()` operations will add up into a shape with many rectangles.

Points 2 and 3 are causing these strange artifacts, especially on subsequent renders like during export (when you hit Cmd + S, it triggers a re-render before grabbing the canvas dataURL).

Here is some updated code to fix these issues:

```js
const canvasSketch = require('canvas-sketch')

const settings = {
  dimensions: [500, 500]
}

const sketch = () => {
  return ({context: ctx, width, height}) => {
    ctx.clearRect(0, 0, width, height) // <-- clear canvas
    ctx.strokeStyle = 'black'
    ctx.lineWidth = 2 // <-- if you want pixel-perfect lines

    const rings = width / 50
    const step = 25
    for (let i = 0; i < rings; i++) {
      const size = width - step * i * 2
      ctx.beginPath() // <-- begin path operation
      ctx.rect(step * i, step * i, size, size)
      ctx.stroke()
    }
  }
}

canvasSketch(sketch, settings)
```

Here is the resulting PNG export, if you look in Photoshop you will see the line width is exactly 2 pixels wide, just like we specified in code.

![2018 08 11-10 30 35](https://user-images.githubusercontent.com/1383811/43990280-ed406310-9d27-11e8-94b3-66dad2d4572b.png)

Another thing you might like is the `{ exportPixelRatio }` setting. This way you can say "line width of 2 pixels" but export at higher DPI. On MBP retina, you really need a 4px line for it to look like a crisp 2px line. Example:

```js
const settings = {
  dimension: [ 500, 500 ],
  exportPixelRatio: 2 // <-- @2x the PNG size
};

// Now render your sketch as before within the 500x500 dimensions,
// and the context will be scaled() on PNG export
// ...
```

**Comment by mattdesl** [comment]
One more thing, in `canvas-sketch@0.0.17` I just pushed a fix that allows you to use `{ pixelRatio }` setting alongside dimensions. So, for example, if you know you are exporting a @2x HDPI image, you can use the following and it will be scaled in browser as well as on export:

```js
const settings = {
  dimension: [ 500, 500 ],
  pixelRatio: 2
};
```

And you could combine with other settings like:

```js
const settings = {
  dimension: [ 500, 500 ],
  // In browser, visualize to your HDPI monitor
  pixelRatio: window.devicePixelRatio,
  // On export, always render with a super high DPI
  exportPixelRatio: 4
};
```

You can update by running this in your project directory:

```sh
npm install canvas-sketch@0.0.17 --save
```

**Comment by Caged** [comment]
> Points 2 and 3 are causing these strange artifacts

🤦‍♂️ can't believe I missed these.  That fixed the color fade issue as expected.  

> One more thing, in canvas-sketch@0.0.17 I just pushed a fix that allows you to use { pixelRatio } setting alongside dimensions. So, for example, if you know you are exporting a @2x HDPI image, you can use the following and it will be scaled in browser as well as on export:

Pulled down the update and per your recommendation, setting `pixelRatio` now reflects a high dpi canvas in the browser!  Thanks for the quick response and fix.  I'd consider this issue closed.
