### ISSUE TITLE
Auto-Installing Modules

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/canvas-sketch#17]
I’d like to unify auto-installation across startup & during development so the user doesn’t need to ‘npm install’. This would also cover glsl deps hopefully.

One concern is that sometimes you will type the wrong package name in require and suddenly you end up pulling in a package you weren’t expecting, maybe even something that causes issues with your machine.

Simple way of supporting auto install: Any time a missing package is found, it gets auto installed and saved as a dependency.

Another, maybe “safer” way: always confirm with the user before installing dependencies. On startup, confirmation would have to happen in the terminal. During dev when a new module is found, confirmation could happen through a browser page with a button to “Install Missing Dependencies”.

I’m leaning toward KISS and just doing the automatic way, but allowing a CLI flag to disable auto installation for more seasoned devs.

**Comment by nkint** [comment]
IMHO a button to “Install Missing Dependencies” or "Confirm to install" is needed. When I used the auto-install in my team we got catastrophic results 😅

Think for example to have a low bandwidth, make a type and auto-download something with a lot of dependencies that can drain a lot of space.. not nice.

Anyway misspelling a dependency name could be a common error specially for people new to javascript ecosystem and could be a bug hard to find.

Some other ideas for safer ways:
- (add a complex piece that I dislike) add a system to check dependencies and track unused ones (use case: misspell, then correct the typo, install the right one.. it is easy to fill package.json with unused garbage..)
- (I like this one because it is simple) create alias for some common packages, like "add 3d-bucket" and it can add `bunny`, `primitive-icosphere`, `angle-normals`, etc

**Comment by mattdesl** [comment]
Thanks for the input @nkint !

The main issue I have with confirmation is that it adds an additional step for newcomers. Right now, you can do this:

```js
canvas-sketch my-sketch.js --new --template=three
```

And it will auto-install any dependencies for that template. This also includes installing a local `canvas-sketch` dependency. It would be a bit annoying to have to confirm each time you start a new sketch (in an empty folder).

I guess I could whitelist "allowed modules" that don't require confirmation — in that case the whitelist would only ever include `canvas-sketch` and `canvas-sketch-util`. This will still require confirmation for things like `three`, `p5`, etc. but perhaps this solution is overall a bit cleaner than auto-installing all the time.

**Comment by mattdesl** [comment]
I am still thinking since this is all about making it easy to sketch / iterate, rather than something like Webpack which is intended to be used in long-term productions across large teams, auto-installation is not going to lead to catastrophic issues like it does in production web dev. Users who wish to avoid the automatic installation could just do:

```sh
canvas-sketch foo.js --no-install
```

Thoughts?

**Comment by nkint** [comment]
Ok, I like it if the focus is the easiness of iteration!

Anyway would be great to have a feedback each time a dependency is downloaded and added. Have thought to any kind of toast notification or similar messages?

**Comment by nkint** [comment]
for example this simple tool has a notification system in the status bar that is quite handy!

https://github.com/gabrielflorit/blockup

internally it uses: https://github.com/mikaelbr/node-notifier

**Comment by mattdesl** [comment]
This is mostly in place now.
