### ISSUE TITLE
Placing two canvas elements on top of each other

### ISSUE THREAD

**Issue by alexalex25** [mattdesl/canvas-sketch#186]
I have tried to put them in { display: block; } but no luck : 

![Screen Shot 2023-07-12 at 12 33 57 AM](https://github.com/mattdesl/canvas-sketch/assets/30702753/4423d32a-c2cd-48f6-a8dd-a8bfb24285b4)

**Comment by mattdesl** [comment]
A potentially simpler way would be to create a second canvas within the first sketch.

```js

const sketch = ({ canvasWidth, canvasHeight }) => {
  const canvas2 = document.createElement('canvas');
  canvas2.width = canvasWidth;
  canvas2.height = canvasHeight;
  const context2 = canvas2.getContext('2d');
  return ({ context, width, height, scaleX, scaleY }) => {
    context2.save();
    context2.scale(scaleX, scaleY);
    /* draw to context2 */
    context2.restore();

    context.drawImage(canvas2, 0, 0, width, height);
  };
}
```

Just to note, this doesn't handle resizing (if you are running your sketch full-screen). 

Another option is to use the code you've got, but use the `{ styleCanvas: false }` setting so that you then apply styles manually to each canvas and have them `position: absolute;` in CSS.

**Comment by alexalex25** [comment]
Thx ! :)
