### ISSUE TITLE
Determine mouse position on canvas

### ISSUE THREAD

**Issue by mhyfritz** [mattdesl/canvas-sketch#42]
Hi Matt.

I was wondering whether there is a built-in way to determine the mouse position on the canvas -- so far I haven't spotted anything along those lines in the docs or examples.

FWIW, here's an [example sandbox](https://codesandbox.io/s/github/mhyfritz/canvas-sketch-with-mouse) how I currently do this.

More generally, I am not sure how to best create a reusable "plugin".  As you can see, I am extending *render props* -- not sure this is necessarily the best idea (might clash with "official" props that you might add in the future). Any recommendations?

Thanks,
Markus

**Comment by mattdesl** [comment]
Hey Markus, cool example! I have not yet considered how to make 'plugins' that are reusable, with React's recent Hooks API I have been considering allowing for something like that in canvas-sketch to safely add side-effects that will be cleaned up on sketch removal.

What you have works, but there are some considerations to be aware of if you want to make a 'fully capable' mouse utility. Since there are lots of things to consider, it would be great if canvas-sketch could have modules like this published somewhere, so you can `require('canvas-sketch-util/mouse')` or something similar.

- Sketches can be removed and disposed of, for example this happens during a hot-reload event, or manually if you decide to dispose of a sketch. In this case you should remove event handlers in your sketch's `dispose()` function
- With different units (cm, inches) and/or different viewport settings, you may get mouse units that are in pixels while all your rendering units are in some other space
- If you are developing a static artwork and want to listen to mouse movement events, you will need to manually call `update()` or `render()` to trigger a new iteration when the mouse moves.

I'll have to think about this a bit more to see how "hooks" or "plugins" could be integrated into canvas-sketch.. 🤔

**Comment by mhyfritz** [comment]
Thanks for the feedback Matt. As I am attaching the event listener on the `canvas` (not `window` or any other parent), I believe I won't need to clean anything up...? Very good point regarding the units, haven't thought of this at all, will wrap my head around this now :)

Oh, and merry Xmas! :santa:

**Comment by Puckapao** [comment]
Hello Matt,

> If you are developing a static artwork and want to listen to mouse movement events, you will need to manually call update() or render() to trigger a new iteration when the mouse moves.

Sorry that I'm not an expert in js but I would like to know or get a demonstration on how to accomplish what you've said. The threejs webgl canvas-sketch project I'm working on need to listen to mouse event and control where the object will go or look at. I really don't understand "manually call update() or render()".
I've tried mhyfritz' solution but it doesn't work well with threejs webgl template.

Thanks,
Puckapao

**Comment by mattdesl** [comment]
Hey @Puckapao —

You can use this template here to handle mouse movements.

https://codesandbox.io/embed/54yv7xylvp

Basically you should get the client XY position of the mouse on the canvas (using mouse events), and then you have to divide that by `{ styleWidth, styleHeight }` props to ensure it is consistent regardless of the dimensions, units and resolution set up in your sketch settings.

You only need to call `update()` manually if you are using a static sketch, e.g. `{ animate }` setting is set to false. If you are using ThreeJS template and `{ animate: true }` then you don't need to manually update or render the canvas, as it re-renders 60 times a second.

**Comment by Puckapao** [comment]
Thank you for fast response Matt. Hope you do update some interaction in later version of this awesome canvas-sketch. 
Have a great day!
