### ISSUE TITLE
Export doubles the frame on save

### ISSUE THREAD

**Issue by TheMapSmith** [mattdesl/canvas-sketch#43]
Hey @mattdesl, love the library, and I'm really appreciative of your support for generative art! 

I'm not totally sure this is the same issue as #25, so I thought I'd open a new issue. 

I've created a script that creates random christmas trees 🎄 

[Code here](https://github.com/TheMapSmith/orn-gen/blob/6b605ea8409541f1ea6669b389b0c2f20cb736d4/tree2.js) _(don't look too closely it's ugly :(_

**Edit: For some reason I made a small tweak to the code (random colors) and now it doesn't do the same thing. I've updated the link above to point to the code at the time that was behaving strangely. The current commit works fine.**

Unfortunately, it isn't exporting correctly. It appears to be leaving the old render in place and then rendering an additional frame on top of it. 

*What's shown on screen:*  
<img width="202" alt="screen shot 2018-12-24 at 11 08 15 pm" src="https://user-images.githubusercontent.com/8357118/50412930-e189b080-07d0-11e9-9465-481890543107.png">

*What's exported to PNG*  
<img width="213" alt="screen shot 2018-12-24 at 11 08 30 pm" src="https://user-images.githubusercontent.com/8357118/50412936-efd7cc80-07d0-11e9-912e-e3508e7c64a1.png">

As far as I can tell this wasn't happening on my previous [ornament-generating code](https://github.com/TheMapSmith/orn-gen/blob/master/sketch.js)

Any ideas?

Thanks!

**Comment by mattdesl** [comment]
Hey @TheMapSmith! Thanks for trying out canvas-sketch.

There are two things in your sketch causing some issues right now:

1. Your `triangle` function is adding lines to a path, but you never call `context.beginPath()` – this means you are always adding commands to one big shape object, even across renders.
2. Your render function is not a "pure" render function — each time it gets called, its resulting in a different visual output (because of the random values).

To fix issue 1, you need to be careful to use `context.beginPath()` when you want to create a new shape:

```js
function triangle(startX, startY, x1, y1, x2, y2) {
  context.fillStyle = 'green'
  // draw a triangle
  context.beginPath();
  context.moveTo(startX, startY);
  context.lineTo(x1, y1)
  context.lineTo(x2, y2)
  context.closePath()
  context.fill()
}
```

There are a number of ways to fix issue 2, but first you must understand why its being rendered multiple times:

When you hit `Cmd + S`, canvas-sketch will re-render your canvas and call your render function again. This is because some props may have changed (like the `{ exporting }` prop), and depending on your settings the final export resolution may not match the browser resolution.

One easy solution is to use a *seeded* random – this means that the random numbers come in a predictable sequence that is the same across renders. It looks like this:

```js
const sketch = () => {
  // First let's generate a totally random seed string
  const seed = random.getRandomSeed();

  return ({ context, width, height }) => {
    // Now, each time we render, reset the randomness to the above seed
    random.setSeed(seed);

    ... the rest of your rendering code ...
  };
};
```

Another solution is to separate the randomness/logic from your rendering code. [Here](https://github.com/mattdesl/canvas-sketch/blob/master/examples/canvas-10-print.js) is one example where the "geometry" is separated from the rendering. Since the data structure doesn't change between renders, it will appear the same even after you hit `Cmd + S` multiple times.

Yet another solution is to forgo a render function entirely (see [here](https://gist.github.com/mattdesl/8940f9461c7b728a10598624c3c00a3a) for an example), and move all of your code to the sketch setup. This means that it will only be rendered once into the canvas. This is a bit less stable – if something changes the `width`/`height` of the canvas, you may lose the contents, or if you are using certain features of canvas-sketch like units, higher resolution exporting etc then it may not resize correctly.

Hope that clears things up a bit! And nice sketch. :smile:

**Comment by TheMapSmith** [comment]
Thanks for the detailed reply with examples, Matt. I realized after my edit last night as I was lying in bed that I also changed the `context.beginPath()` portion of my `triangle()` function, which probably accounted for the fix. Thanks again for all you do!
