### ISSUE TITLE
How to handle env var?

### ISSUE THREAD

**Issue by 0m15** [mattdesl/canvas-sketch#65]
First, thanks for this great project.
I'd like to handle env var. I'm just trying with https://www.npmjs.com/package/babel-plugin-transform-inline-environment-variables but without any success. 
I see `process.env` empty.

Any advice?

**Comment by mattdesl** [comment]
Environment variables are inlined at bundle-time rather than passing all env vars into the JavaScript bundle (which could lead to some sensitive information being placed into JS without it being obvious to most devs). So to use it you can do this:

```sh
HELLO=world canvas-sketch foo.js
```

```js
// Should print 'world'
console.log(process.env.HELLO);
```

By default `NODE_ENV` will be equal to `'development'` during dev, and `'production'` when using the `--build` flag.

**Comment by mattdesl** [comment]
Closing as this seems resolved. Feel free to comment here if you need something else around env vars.
