### ISSUE TITLE
Why use `global` when attaching global object

### ISSUE THREAD

**Issue by fnick851** [mattdesl/canvas-sketch#95]
This is probably documented somewhere but I couldn't find it.

For example, `global.THREE = require("three");`:
Why not just `window.THREE = require("three");`? Is there anything special about this?
Also, is it `browserify` that transpiles `global` under the hood to `window` when serving to browser?

Thanks.

**Comment by mattdesl** [comment]
Good question! Browserify will inject a global variable into each script called `global`, which points to `window`, imagine this:

```js
(function (global) { // <-- injected by Browserify
global.THREE = /* ... */; // <-- your script code
})(window); // <-- injected by browserify
```

The reason is because Node.js uses the variable `global` instead of `window`. So, if you use `global` instead of `window`, then your code will run the same in both Node.js and the browser, for example using the [gl](https://www.npmjs.com/package/gl) module to render a ThreeJS scene on the server.

**Comment by fnick851** [comment]
@mattdesl Thanks!
